server:
  port: 7000
  servlet:
    context-path: /ad-sponsor #访问前缀
eureka:
  client:
    service-url:
      defaultZone: http://server1:8000/eureka/
spring:
  application:
    name: service-ad-sponsor
  datasource:
    url: jdbc:mysql://121.40.177.19:3306/alone_ad_data?characterEncoding=utf8&useSSL=false&serverTimezone=UTC&rewriteBatchedStatements=true
    username: root
    password: root
    tomcat:
      max-active: 4
      min-idle: 2
      initial-size: 2

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml #xml文件地址
  type-aliases-package: com.alone.*.entity #实体类包扫描
  type-handlers-package: come.alone.*.handlers # typehandlers包扫描
  check-config-location: true # 启动时是否检查 MyBatis XML 文件的存在
  global-config:
    db-config:
      id-type: assign_id # 雪花算法
      table-underline: true #表格大小写
      logic-delete-field: isDelete # 全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1 # 逻辑已删除值(默认为 1)
      logic-not-delete-value: 0 # 逻辑未删除值
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl #打印sql日志

